# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Catppuccin Mocha color palette
palette = "catppuccin_mocha"

format = """
[╭─](overlay0) $all\
$fill\
$time\
$line_break\
[╰─](overlay0) $character
"""

# Inserts a blank line between shell prompts
add_newline = true

[fill]
symbol = " "

# Character con colores Catppuccin
[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[line_break]
disabled = false

# Time module con mejor formato
[time]
disabled = false
format = '[ 󰥔 $time ](blue)'
time_format = "%H:%M"

# Directory con íconos y colores
[directory]
format = "[ 󰉋 $path ]($style)"
style = "blue"
truncation_length = 3
truncation_symbol = "…/"

# Git branch
[git_branch]
format = "[ 󰊢 $branch ]($style)"
style = "green"

# Git status
[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "yellow"

# Package version
[package]
format = "[ 󰏗 $version ]($style)"
style = "peach"

# Node.js
[nodejs]
format = "[ 󰎙 $version ]($style)"
style = "green"

# Python
[python]
format = '[ 󰌠 $version(\($virtualenv\)) ]($style)'
style = "yellow"

# Rust
[rust]
format = "[ 󱘗 $version ]($style)"
style = "red"

# Command duration
[cmd_duration]
format = "[ 󰔛 $duration ]($style)"
style = "overlay0"
min_time = 2000

# Catppuccin Mocha palette definition
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
