# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt simple y limpio: julisa@julixos:~/ >
format = """
$username@$hostname:$directory $character"""

# No líneas en blanco adicionales
add_newline = false

# Configuración del usuario
[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style)"

# Configuración del hostname
[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold green"

# Configuración del directorio
[directory]
format = "[$path]($style)"
style = "bold cyan"
truncation_length = 0
truncate_to_repo = false

# Configuración del carácter del prompt
[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"

# Deshabilitar todos los otros módulos
[git_branch]
disabled = true

[git_status]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_commit]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[php]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true

[memory_usage]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[azure]
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[custom]
disabled = true

[sudo]
disabled = true

[cmd_duration]
disabled = true

[line_break]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[status]
disabled = true

[container]
disabled = true

[shell]
disabled = true

[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"
